# Generated by Django 4.2.7 on 2023-12-13 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='project',
        ),
    ]
