# Generated by Django 4.2.7 on 2023-12-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_client_feedback_client_logo_contact_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coc', models.IntegerField()),
                ('pc', models.IntegerField()),
                ('hc', models.IntegerField()),
                ('collab', models.IntegerField()),
            ],
        ),
    ]
